load("//testing/rules:defs.bzl", "test_runner")

test_runner(
    name = "BuiltinRulesTest",
    fixture = "//testing/fixtures/cpp:builtin",
    test = "BuiltinRulesTest.kt",
)

test_runner(
    name = "ToolDepTest",
    fixture = "//testing/fixtures/cpp:tool",
    test = "ToolDepTest.kt",
)

test_runner(
    name = "XcodeTest",
    fixture = "//testing/fixtures/cpp:simple",
    test = "XcodeTest.kt",
)
