load("//testing/rules:defs.bzl", "test_runner")

test_runner(
    fixture = "//testing/fixtures/cpp:builtin",
    test = "BuiltinRulesTest.kt",
)

test_runner(
    fixture = "//testing/fixtures/cpp:tool",
    test = "ToolDepTest.kt",
)

test_runner(
    fixture = "//testing/fixtures/cpp:simple",
    test = "ToolchainTest.kt",
)
