load("//testing/rules:defs.bzl", "test_runner")

test_runner(
    name = "TargetTest",
    fixture = "//testing/fixtures/cpp:simple",
    test = "TargetTest.kt",
)

test_runner(
    name = "BuildFileTest",
    fixture = "//testing/fixtures/cpp:simple",
    test = "BuildFileTest.kt",
)

test_runner(
    name = "TransitionTest",
    fixture = "//testing/fixtures/cpp:transition",
    test = "TransitionTest.kt",
)
