load("//testing/rules:defs.bzl", "test_runner")

test_runner(
    name = "PyBinaryTest",
    fixture = "//testing/fixtures/python:args",
    test = "PyBinaryTest.kt",
)

test_runner(
    name = "PyLibraryTest",
    fixture = "//testing/fixtures/python:simple",
    test = "PyLibraryTest.kt",
)

test_runner(
    name = "PyTestTest",
    fixture = "//testing/fixtures/python:simple",
    test = "PyTestTest.kt",
)
