load("//testing/rules:defs.bzl", "test_runner")

test_runner(
    fixture = "//testing/fixtures/python:args",
    test = "PyBinaryTest.kt",
)

test_runner(
    fixture = "//testing/fixtures/python:simple",
    test = "PyLibraryTest.kt",
)

test_runner(
    fixture = "//testing/fixtures/python:simple",
    test = "PyTestTest.kt",
)
